name: 'Sync Branch Action'
description: 'Action to update branches automatically.'
author: 'Lucas Ruy'

branding:
  icon: git-merge
  color: purple

inputs:
  GITHUB_TOKEN:
    description: 'User token to be associated with this pull request.'
    required: true
  SOURCE_BRANCH:
    description: 'Branch where you implemented your new code.'
    required: true
  DESTINATION_BRANCH:
    description: 'Branch you want to send your new code.'
    required: true
  PULL_REQUEST_TITLE:
    description: 'Standard title for your update pull request. Default is: "update: {FROM_BRANCH} to {TO_BRANCH}"'
    required: false
  PULL_REQUEST_BODY:
    description: 'Content with description for your automated pull. Default is: "This is an automatic PullRequest to keep {BASE_BRANCH} up to date with {FROM_BRANCH}!"'
    required: false
  PULL_REQUEST_LABEL:
    description: 'Pull Request label. Default is: ""'
    required: false

outputs:
  PULL_REQUEST_URL:
    description: "The url of the generated pull request."

runs:
  using: 'node16'
  main: 'dist/index.js'
