name: "Tests"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

