name: "Tests"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm test