name: "Sync main branch"

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup environment"
        uses: actions/checkout@v3

      - name: "Create update pull request"
        uses: LucasRuy/sync-branch-action@v1.1.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SOURCE_BRANCH: 'develop'
          DESTINATION_BRANCH: 'main'
